main/urls.py
from django.urls import path

from . import views

app_name = "main"

urlpatterns = [
    path("", views.home, name="home"),
    path("sukses", views.sukses),
    path("login", views.login, name="login"),
    path("logout", views.logout, name="logout"),
    path("register", views.register, name="register"),
    path("register-admin", views.register_admin, name="register-admin"),
    path("register-user", views.register_user, name="register-user"),
    path("register-user-individu", views.register_user_individu, name="register-user-individu"),
    path("register-user-organisasi", views.register_user_organisasi, name="register-user-organisasi"),
    path("admin-sidona/list-pengguna", views.list_pengguna_terdaftar, name="list_pengguna"),
    path('logout/',views.logout, name='logout')
]

penggalangan_dana/urls.py
from django.urls import path

from . import views

app_name = "penggalangan_dana"

urlpatterns = [
    path("", views.daftar_penggalangan, name="daftar"),
    path("admin", views.daftar_penggalangan_admin, name="daftar_admin"),
    path("PD", views.daftar_penggalangan_PD, name="daftar_PD"),
    path("Delete/<str:id>/", views.delete, name="delete"),
    path("Deletekomorbid/<str:id>/", views.deleteKomorbid, name="delete_komorbid"),
    path("update", views.form_update, name="form_update"),
    path("form_verifikasi", views.form_verifikasi, name="form_verifikasi"),
    path("detail/<str:id>/", views.detail_penggalangan),
    path("komorbid", views.komorbid, name="komorbid"),
    path("komorbid/tambah", views.komorbid_tambah, name="komorbid_tambah"),
    path("komorbid/update/<str:id>/", views.komorbid_update, name="komorbid_update"),
    path("create", views.create_PD_category, name="create_PD_category"),
    path("create/cekpasien", views.cek_pasien, name="cek_pasien"),
    path("create/cekrumah", views.cek_rumah, name="cek_rumah"),
    path("create/daftarrumah", views.daftar_rumah, name="daftar_rumah"),
    path("create/daftarpasien", views.daftar_pasien, name="daftar_pasien"),
    path("create/form_PD", views.form_PD, name="form_PD"),
    path("kategori/tambah", views.form_tambah_kategori),
    path("kategori/", views.list_kategori),
    path("kategori/update", views.form_update_kategori),
]

sidona/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls")),
    path("penggalangan/", include("penggalangan_dana.urls")),
    path("pencairan/", include("pencairanDana.urls")),
    path("donasi/", include("donasi.urls")),
]

penggalangan_dana/views.py
from django.http import response, JsonResponse
from django.core.exceptions import SuspiciousOperation
from django.shortcuts import render, redirect
from django.db import connection
import penggalangan_dana
import datetime
from random import randrange
from penggalangan_dana.utils import namedtuple_fetch_all



def daftar_penggalangan(request):
    cursor_p = connection.cursor()
    query = """
            SELECT pd.id, judul, kota, provinsi, tanggal_aktif_akhir, sisa_hari, jumlah_dibutuhkan, nama_kategori
            FROM sidona.penggalangan_dana_pd pd, sidona.kategori_pd k
            WHERE pd.id_kategori = k.id AND status_verifikasi = 'Terverifikasi' AND sisa_hari > 0;
            """
    cursor_p.execute(query)
    pds = namedtuple_fetch_all(cursor_p)
    return render(request, "penggalangan/daftar_penggalangan.html", {"pds": pds})


def daftar_penggalangan_admin(request):
    cursor_p = connection.cursor()
    query = """
            SELECT pd.id, judul, kota, provinsi, tanggal_aktif_awal, tanggal_aktif_akhir, sisa_hari, jumlah_dibutuhkan, nama_kategori, status_verifikasi
            FROM sidona.penggalangan_dana_pd pd, sidona.kategori_pd k
            WHERE pd.id_kategori = k.id;
            """
    cursor_p.execute(query)
    pds = namedtuple_fetch_all(cursor_p)
    return render(request, "penggalangan/admin/daftar_penggalangan.html", {"pds": pds})


def daftar_penggalangan_PD(request):
    with connection.cursor() as cursor:
        cursor.execute("select pd.id, pd.judul, pd.kota, pd.provinsi, pd.tanggal_aktif_awal, pd.tanggal_aktif_akhir, pd.sisa_hari, pd.jumlah_dibutuhkan, k.nama_kategori, pd.status_verifikasi from penggalangan_dana_pd pd, penggalang_dana p, kategori_pd k where pd.email_user = p.email and pd.id_kategori=k.id and pd.email_user = %s",[request.session.get("username")])
        result = namedtuple_fetch_all(cursor)
        cursor.execute("select jumlah_pd from penggalang_dana where email=%s",[request.session.get("username")])
        jumlah_pd = cursor.fetchall()[0][0]
        cursor.execute("select jumlah_pd_aktif from penggalang_dana where email=%s",[request.session.get("username")])
        jumlah_pd_aktif = cursor.fetchall()[0][0]
        response ={
            "hasil":result,
            "jumlah":jumlah_pd,
            "aktif":jumlah_pd_aktif
        }
        print(result)
    return render(request, "penggalangan/admin/daftar_PD_pribadi.html", response)


def form_update(request):
    id = request.GET.get("id", "")
    if not id:
        raise SuspiciousOperation("No ID Provided")
    cursor_p = connection.cursor()
    query = (
        """
        SELECT pd.id, pd.judul, pd.deskripsi, pd.kota, pd.provinsi, pd.tanggal_aktif_akhir,
            pd.jumlah_dibutuhkan, pd.status_verifikasi, k.nama_kategori
        FROM penggalangan_dana_pd pd, kategori_pd k
        WHERE id_kategori in (
            SELECT id
            FROM kategori_pd
            WHERE id = pd.id_kategori
        )  AND pd.id = '{}';
        """.format(id)
    )
    cursor_p.execute(query)
    pd = namedtuple_fetch_all(cursor_p)

    response = {
        "pd": pd[0],
    }

    if getattr(pd[0], 'nama_kategori') == 'kesehatan':
        query = (
            """
            SELECT p.nik, p.nama, pdk.penyakit, k.komorbid
            FROM pd_kesehatan pdk, pasien p, komorbid k, penggalangan_dana_pd pdpd
            WHERE k.idpd in (
                SELECT idpd
                FROM komorbid
                WHERE komorbid.idpd = pdpd.id
            ) AND pdk.idpd = '{}' AND pdk.idpasien = p.nik
            """.format(getattr(pd[0], 'id'), getattr)
        )
        cursor_p.execute(query)
        pdk = namedtuple_fetch_all(cursor_p)
        response["pdk"] = pdk
    elif getattr(pd[0], 'nama_kategori') == 'rumah_ibadah':
        pass

    return render(request, "penggalangan/form_update.html", response)


def form_verifikasi(request):
    return render(request, "penggalangan/form_verifikasi.html")


def form_tambah_kategori(request):
    return render(request, "penggalangan/kategori/form_tambah.html")


def list_kategori(request):
    with connection.cursor() as cursor:
        cursor.execute("SELECT * FROM kategori_pd")
        result = namedtuple_fetch_all(cursor)
        response ={
            "kategoris": result
        }
    return render(request, "penggalangan/kategori/list.html", response)


def form_update_kategori(request):
    response = {}

    if request.method == 'POST':
        id = request.POST["id"]
        nama = request.POST["nama"]
        with connection.cursor() as cursor:
            cursor.execute("UPDATE kategori_pd SET nama_kategori = '{nama}' WHERE id = '{id}';".format(nama=nama, id=id))
            response["message"] = "Sukses mengupdate kategori!"

    id = request.GET.get("id", "")
    if not id: return redirect('/penggalangan/kategori/')
    with connection.cursor() as cursor:
        cursor.execute("SELECT * FROM kategori_pd WHERE id = '{}'".format(id))
        result = namedtuple_fetch_all(cursor)
        response["k"] = result[0]

    return render(request, "penggalangan/kategori/form_update.html", response)


def detail_penggalangan(request):
    id = request.GET.get("id", "1")
    response = {"id": id}
    return render(request, "penggalangan/detail_penggalangan.html", response)

def delete(request, id):
    with connection.cursor() as cursor:
        cursor.execute("delete from penggalangan_dana_pd where id=%s",[id])
    return redirect("penggalangan_dana:daftar_PD")

def deleteKomorbid(request, id):
    with connection.cursor() as cursor:
        cursor.execute("delete from komorbid where idPD=%s",[id])
    return redirect("penggalangan_dana:komorbid")

def create_PD_category(request):
    with connection.cursor() as cursor:
        cursor.execute("select nama_kategori from sidona.kategori_pd")
        kategori = cursor.fetchall()
        response ={
            "kategori" : kategori,
        }
        if request.method == "POST":
            category = request.POST["category"]

            response = {}
            response["email"]=request.session["username"]
            response["id"] = increment_id_pd(request,category)
            response["category"] = category
            return render(
                request, "penggalangan/create_PD/form_penggalangan_dana.html", response
            )

    return render(request, "penggalangan/create_PD/form_kategori.html", response)

def increment_id_pd(request, kategori):
    with connection.cursor() as cursor:
        user = request.session["username"]
        cursor.execute("select id from penggalangan_dana_pd where email_user=%s order by id desc limit 1",[user])
        newID = cursor.fetchall()
        if(len(newID)>0):
            if(newID[0][0][1]!="-"):
                newID= str(int(newID[0][0])+1)
                newID = kategori[0]+"-"+newID
            else:
                newID= str(int(newID[0][0][2:-1])+1)
                newID = kategori[0]+"-"+newID
        else:
            newID = kategori[0]+"-001"
    return newID


def cek_pasien(request):
    with connection.cursor() as cursor:
        if request.method == "POST":
            nik = request.POST["NIK"]
            cursor.execute("select nik from sidona.pasien where nik = %s", [nik])
            result = cursor.fetchall()
            if(len(result)==0):
                response = {
                    "warning":"gagal"
                }
                return render(request, "penggalangan/create_PD/cek_pasien.html",response)
            response = {}
            response["email"]=request.session["username"]
            cursor.execute("select nama from sidona.pasien where nik = %s", [nik])
            response["category"] = "Kesehatan"
            response["NIK"] = nik
            response["nama"] = cursor.fetchall()
            response["id"] = increment_id_pd(request,"Kesehatan")
            return render(request, "penggalangan/create_PD/form_penggalangan_dana.html", response)

    return render(request, "penggalangan/create_PD/cek_pasien.html")


def cek_rumah(request):
    with connection.cursor() as cursor:
        if request.method == "POST":
            noSertif = request.POST["noSertif"]
            cursor.execute("select nosertifikat from sidona.rumah_ibadah where nosertifikat = %s", [noSertif])
            result = cursor.fetchall()
            if(len(result)==0):
                response = {
                    "warning":"gagal"
                }
                return render(request, "penggalangan/create_PD/cek_rumah_ibadah.html",response)
            response = {}
            response["email"]=request.session["username"]
            response["category"] = "Rumah Ibadah"
            response["noSertif"] = noSertif
            cursor.execute("select nama from sidona.kategori_aktivitas_pd_rumah_ibadah")
            response["kategori"] = cursor.fetchall()
            response["id"] = increment_id_pd(request, "Rumah Ibadah")
            return render(request, "penggalangan/create_PD/form_penggalangan_dana.html", response)

    return render(request, "penggalangan/create_PD/cek_rumah_ibadah.html")


def daftar_pasien(request):
    with connection.cursor() as cursor:
        if request.method == "POST":
            nik = request.POST["NIK"]
            nama = request.POST["Nama"]
            tanggal = request.POST["Tanggal"]
            alamat = request.POST["Alamat"]
            pekerjaan = request.POST["Pekerjaan"]
            cursor.execute("insert into pasien values (%s,%s,%s,%s,%s)",[nik, nama, tanggal, alamat, pekerjaan])
            cursor.execute("select nama from sidona.pasien where nik = %s", [nik])
            response = {}
            response["email"]=request.session["username"]
            response["category"] = "Kesehatan"
            response["NIK"] = nik
            response["nama"] = cursor.fetchall()
            response["id"] = increment_id_pd(request,"Kesehatan")

penggalangan_dana/templates/penggalangan/create_PD/cek_pasien.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Cek Pasien</title>
{% endblock meta %}

{% block content %}
<h2>CEK PASIEN YANG TERDAFTAR</h2>
<form action="" method="post">
  {% csrf_token %}
  {% if warning %}
    <h2>Pasien Tidak Ditemukan!</h2>
  {% endif %}
  <label for="NIK">NIK Pasien: </label>
  <input type="text" id="NIK" name="NIK" required><br>
  <button type="submit"> Next </button>
</form>
{% endblock content %}

penggalangan_dana/templates/penggalangan/create_PD/cek_rumah_ibadah.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
<h2>CEK RUMAH IBADAH YANG TERDAFTAR</h2>
<form action="" method = "post">
  {% csrf_token %}
  {% if warning %}
    <h2>Rumah Ibadah Tidak Ditemukan!</h2>
  {% endif %}
  <label for="noSertif">Nomor Sertifikat Rumah Ibadah: </label>
  <input type="text" id="No Sertif" name="noSertif" required><br>
  <button type="submit"> Next </button>
</form>
{% endblock content %}

penggalangan_dana/templates/penggalangan/create_PD/form_kategori.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Select Category</title>
{% endblock meta %}

{% block content %}
<div class="alert alert-primary" role="alert", id="KesehatanChoice", style="display: none;">
  <h5>Masukkan Data Pasien Baru?</h5>
  <a class="btn btn-primary" href="{% url 'penggalangan_dana:daftar_pasien' %}" role="button">Ya</a>
  <a class="btn btn-primary" href="{% url 'penggalangan_dana:cek_pasien' %}" role="button">Tidak</a>
</div>

<div class="alert alert-primary" role="alert", id="RumahIbadahChoice", style="display: none;">
  <h5>Masukkan Data Rumah Ibadah Baru?</h5>
  <a class="btn btn-primary" href="{% url 'penggalangan_dana:daftar_rumah' %}" role="button">Ya</a>
  <a class="btn btn-primary" href="{% url 'penggalangan_dana:cek_rumah' %}" role="button">Tidak</a>
</div>

<h4>Select Your Category</h4>
<form action="", method="post", onsubmit="submitForm(event)">
  {% csrf_token %}
  <select name="category", id="category">
    {% for k in kategori%}
      <option>{{k.0}}</option>
    {% endfor %}
  </select>
  <button type="submit"> Next </button>
</form>
<script type="text/JavaScript">
  function submitForm(event){
    var category = document.getElementById("category").value;
    if(category === "kesehatan"){
      event.preventDefault();
      if(document.getElementById("RumahIbadahChoice").style.display==="block"){
        document.getElementById("RumahIbadahChoice").style.display = "None";
      }
      document.getElementById("KesehatanChoice").style.display = "block";
    }
    else if(category ==="rumah ibadah"){
      event.preventDefault();
      if(document.getElementById("KesehatanChoice").style.display==="block"){
        document.getElementById("KesehatanChoice").style.display = "None";
      }
      document.getElementById("RumahIbadahChoice").style.display = "block";
    }
  }
</script>
{% endblock content %}

penggalangan_dana/templates/penggalangan/create_PD/form_pasien.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Form Pasien Baru</title>
{% endblock meta %}

{% block content %}
<h2>DAFTARKAN PASIEN BARU</h2>
<form class="mt-4 border p-4" style="max-width: 640px;" action="" method="post">
  {% csrf_token %}
  <div class="form-group">
    <label for="NIK">NIK: </label>
    <input type="text" class="form-control" id="NIK" name="NIK" required>
  </div>
  <div class="form-group">
    <label for="Nama">Nama: </label>
    <input type="text" class="form-control" id="Nama" name="Nama" required>
  </div>
  <div class="form-group">
    <label for="Tanggal">Tanggal Lahir: </label>
    <input type="date" class="form-control" id="Tanggal" name="Tanggal" required>
  </div>
  <div class="form-group">
    <label for="Alamat">Alamat: </label>
    <input type="text" class="form-control" id="Alamat" name="Alamat" required>
  </div>
  <div class="form-group">
    <label for="Pekerjaan">Pekerjaan: </label>
    <input type="text" class="form-control" id="Pekerjaan" name="Pekerjaan" required>
  </div>
  <button type="submit"> Next </button>
</form>
{% endblock content %}

penggalangan_dana/templates/penggalangan/create_PD/form_penggalangan_dana.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Form Penggalangan Dana</title>
{% endblock meta %}

{% block content %}
<h1>Form Penggalangan Dana</h1>
<form class="mt-4 border p-4" style="max-width: 640px;" action= "/penggalangan/create/form_PD"method="post">
  {% csrf_token %}
  <h4>Informasi Umum Penggalangan Dana</h4>
  <div class="form-group">
    <label>ID Penggalangan Dana</label>
    <input type="text" class="form-control" name="id"value ="{{id}}"readonly>
  </div>
  <div class="form-group">
    <label>Email</label>
    <input type="email" class="form-control" value="{{email}}" readonly>
  </div>
  <div class="form-group">
    <label>Judul</label>
    <input type="text" class="form-control" name="judul" placeholder="Masukkan judul" required>
  </div>
  <div class="form-group">
    <label>Deskripsi</label>
    <input type="text" class="form-control" name="deskripsi" placeholder="Masukkan deskripsi" required>
  </div>
  <div class="form-group">
    <label>Kota</label>
    <input type="text" class="form-control" name="kota" placeholder="Masukkan kota" required>
  </div>
  <div class="form-group">
    <label>Provinsi</label>
    <input type="text" class="form-control" name="provinsi" placeholder="Masukkan provinsi" required>
  </div>
  <div class="form-group">
    <label>Deadline Penggalangan Dana</label>
    <input type="text" class="form-control" name="deadline" placeholder="Masukkan Deadline Penggalangan Dana" required>
  </div>
  <div class="form-group">
    <label>Jumlah Target Dana (Rupiah)</label>
    <input type="text" class="form-control" name="target" placeholder="Masukkan Target Dana" required>
  </div>
  <hr />
  <h4>Informasi Tambahan Penggalangan Dana</h4>
  <div class="form-group">
    <label>Kategori</label>
    <input type="text" class="form-control" name="category"value={{category}} readonly>
  </div>
  {% if category == "Kesehatan" %}
  <div class="form-group">
    <label>NIK Pasien:</label>
    <input type="text" class="form-control" name="NIK" value="{{NIK}}" readonly>
  </div>
  <div class="form-group">
    <label>Nama Pasien:</label>
    <input type="text" class="form-control" name="namaPasien" value="{{nama.0.0}}" readonly>
  </div>
  <div class="form-group">
    <label>Penyakit Utama:</label>
    <input type="text" class="form-control" name="penyakit" placeholder="Masukkan Penyakit Utama" required>
  </div>
  
  {% elif category == "Rumah Ibadah" %}
  <div class="form-group">
    <label>Nomor Sertifikat Rumah Ibadah:</label>
    <input type="text" class="form-control" name="noSertif" value = "{{noSertif}}" readonly>
  </div>
  <div class="form-group">
    <label>Kategori Aktivitas:</label>
    <select name="select" class="form-control" id="select" required>
      <option selected>Choose...</option>
      {% for k in kategori%}
      <option>{{k.0}}</option>
      {% endfor %}
    </select>
  </div>
  {% endif %}
  <div class="form-group">
    <label>Berkas Penggalangan Dana:</label>
    <input type="text" class="form-control" name="link" placeholder="Masukkan Link Berkas" required>
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock content %}

penggalangan_dana/templates/penggalangan/create_PD/form_rumah_ibadah.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Form Rumah Ibadah</title>
{% endblock meta %}

{% block content %}
<h2>DAFTARKAN RUMAH IBADAH</h2>
<form class="mt-4 border p-4" style="max-width: 640px;" action="" method = "post">
  {% csrf_token %}
  <div class="form-group">
    <label for="noSertif">Nomor Sertifikat: </label>
    <input type="text" class="form-control" id="No Sertif" name="noSertif" required><br>
  </div>
  <div class="form-group">
    <label for="Nama">Nama: </label>
    <input type="text" class="form-control" id="Nama" name="Nama" required><br>
  </div>
  <div class="form-group">
    <label for="Alamat">Alamat: </label>
    <input type="text" class="form-control" id="Alamat" name="Alamat" required><br>
  </div> 
  <div class="form-group">
    <label for="Jenis">Jenis: </label>
    <input type="text" class="form-control" id="Jenis" name="Jenis" required><br>
  </div>
  <button type="submit"> Next </button>
</form>
{% endblock content %}