main/urls.py
from django.urls import path

from . import views

app_name = "main"

urlpatterns = [
    path("", views.home, name="home"),
    path("sukses", views.sukses),
    path("login", views.login, name="login"),
    path("logout", views.logout, name="logout"),
    path("register", views.register, name="register"),
    path("register-admin", views.register_admin, name="register-admin"),
    path("register-user", views.register_user, name="register-user"),
    path("register-user-individu", views.register_user_individu, name="register-user-individu"),
    path("register-user-organisasi", views.register_user_organisasi, name="register-user-organisasi"),
    path("admin-sidona/list-pengguna", views.list_pengguna_terdaftar, name="list_pengguna"),
    path('logout/',views.logout, name='logout')
]

penggalangan_dana/urls.py
from django.urls import path

from . import views

app_name = "penggalangan_dana"

urlpatterns = [
    path("", views.daftar_penggalangan, name="daftar"),
    path("admin", views.daftar_penggalangan_admin, name="daftar_admin"),
    path("PD", views.daftar_penggalangan_PD, name="daftar_PD"),
    path("Delete/<str:id>/", views.delete, name="delete"),
    path("Deletekomorbid/<str:id>/", views.deleteKomorbid, name="delete_komorbid"),
    path("update", views.form_update, name="form_update"),
    path("form_verifikasi", views.form_verifikasi, name="form_verifikasi"),
    path("detail/<str:id>/", views.detail_penggalangan),
    path("komorbid", views.komorbid, name="komorbid"),
    path("komorbid/tambah", views.komorbid_tambah, name="komorbid_tambah"),
    path("komorbid/update/<str:id>/", views.komorbid_update, name="komorbid_update"),
    path("create", views.create_PD_category, name="create_PD_category"),
    path("create/cekpasien", views.cek_pasien, name="cek_pasien"),
    path("create/cekrumah", views.cek_rumah, name="cek_rumah"),
    path("create/daftarrumah", views.daftar_rumah, name="daftar_rumah"),
    path("create/daftarpasien", views.daftar_pasien, name="daftar_pasien"),
    path("create/form_PD", views.form_PD, name="form_PD"),
    path("kategori/tambah", views.form_tambah_kategori),
    path("kategori/", views.list_kategori),
    path("kategori/update", views.form_update_kategori),
]

sidona/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls")),
    path("penggalangan/", include("penggalangan_dana.urls")),
    path("pencairan/", include("pencairanDana.urls")),
    path("donasi/", include("donasi.urls")),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
      integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    {% block meta %} {% endblock meta %}
  </head>

  <body>
    {% include 'navbar.html' %}
    <div class="p-4">
    {% block content %}
    {% endblock content %}
    </div>
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

templates/navbar.html
<head>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" />

  <style>
    #profile{
      position: absolute;
      top: 0;
      right: 0;
      padding: 0;
      margin: 0;
    }
  </style>
  



</head>








<nav class="navbar navbar-expand-lg navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="/">SIDONA</a>
  <button
    class="navbar-toggler"
    type="button"
    data-toggle="collapse"
    data-target="#navbarNavAltMarkup"
    aria-controls="navbarNavAltMarkup"
    aria-expanded="false"
    aria-label="Toggle navigation"
  >
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <ul class="navbar-nav mr-auto">
    <div class="navbar-nav">
      <a class="nav-item nav-link {% if request.resolver_match.url_name == 'home' %} active{% endif %}" href="/">Home</a>
      <a class="nav-item nav-link {% if request.resolver_match.url_name == 'list_pengguna' %} active{% endif %}" href="/admin-sidona/list-pengguna">List Pengguna</a>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Penggalangan Dana
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'penggalangan_dana:daftar' %}">Daftar Penggalangan Dana</a>
          <a class="dropdown-item" href="{% url 'penggalangan_dana:daftar_admin' %}">Daftar Penggalangan Dana (Admin)</a>
          <a class="dropdown-item" href="{% url 'penggalangan_dana:daftar_PD' %}">Daftar Penggalangan Dana (Penggalang Dana)</a>
          <a class="dropdown-item" href="{% url 'penggalangan_dana:komorbid' %}">Kelola Komorbid</a>
          <a class="dropdown-item" href="{% url 'penggalangan_dana:create_PD_category' %}">Buat Penggalangan Dana</a>
          <a class="dropdown-item" href="/penggalangan/update">Form Update Penggalangan Dana</a>
          <a class="dropdown-item" href="/penggalangan/form_verifikasi">Form Verifikasi Penggalangan Dana</a>
          <a class="dropdown-item" href="/penggalangan/detail">Detail Penggalangan Dana</a>
          <a class="dropdown-item" href="/penggalangan/kategori">List Kategori Penggalangan Dana</a>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Donasi
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="/donasi">Data Donasi Penggalangan Dana</a>
        </div>
      </li>
      {% if not request.session.username %}
      <a class="nav-item nav-link" href="/login">Login</a>
      {% endif %}
    </ul>
      
    {% if request.session.username %}
      <ul class="navbar-nav ml-auto">
        <li class="nav-item dropdown">
          
          <a class="nav-link dropdown-toggle waves-effect waves-light" id="navbarDropdownMenuLink-4" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-user"></i></a>
          <div class="dropdown-menu dropdown-menu-right dropdown-info" aria-labelledby="navbarDropdownMenuLink-4">
            {% if request.session.peran == 'penggalang_dana' %}
            <a class="dropdown-item waves-effect waves-light" href="/pencairan/profile">My Profile</a>
            {% endif %}
            <a class="dropdown-item waves-effect waves-light" href="/logout/">Log out</a>
          </div>
        </li>
      </ul>
      {% endif %}


  
    </div>
  </div>
</nav>